export enum NOTIFICATION_TYPE_ENUM {
  UPCOMING_EVENT = 1,
  REGISTRATION_BE_CONFIRMED = 2,
  NEW_CONTRACT = 3,
  CHECKOUT_COMPLETED = 4,
  POST_REOPENED = 5,
  APPLICATION = 6,
  INTERVIEW_DAY = 7,
  INTERVIEW_RESULT = 8,
  CHECKOUT_CONFIRMED = 9,
}
